global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 31.220.31.4:9091
- job_name: linux-exporter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 31.220.31.4:9100
- job_name: nginx-exporter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 31.220.31.4:9113
- job_name: kudu-master
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics_prometheus
  scheme: http
  static_configs:
  - targets:
    - 31.220.31.4:8051
    - 31.220.31.4:8151
    - 31.220.31.4:8251
- job_name: kudu-tablet
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics_prometheus
  scheme: http
  static_configs:
  - targets:
    - 31.220.31.4:8050
    - 31.220.31.4:8150
    - 31.220.31.4:8250
